name: Dev CI

on:
  push:
    branches: [ master, piyush/cache-invalid ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ".env.local"
        contents: "REACT_APP_API_ENDPOINT=http://api.staging.control.cov2.in/api/"
        write-mode: "overwrite"
    
    - name: Read file
      run: cat .env.local
    
    - name: list files
      run: ls -l
    
    - name: Yarn Install Dependencies
      uses: CultureHQ/actions-yarn@v1.0.1
      with:
        args: install
    
    - name: npm run build
      run: npm run build
    
    - name: Log npm errors
      if: failure()
      run: cat /home/runner/.npm/_logs/*
      
    - name: List build directory
      run: ls -R build/
    
    - name: Upload everything except index.html to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --cache-control 'max-age=86400' --exclude index.html
      env:
        AWS_S3_BUCKET: 'control.covid-dev'
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        AWS_REGION: 'ap-south-1'
        SOURCE_DIR: 'build'
        DEST_DIR: 'build'

    - name: Upload index.html to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --cache-control 'no-cache'
      env:
        AWS_S3_BUCKET: 'control.covid-dev'
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
        AWS_REGION: 'ap-south-1'
        SOURCE_DIR: 'build'
        DEST_DIR: 'build'
