name: Prod CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: '.env.local'
          contents: 'REACT_APP_API_ENDPOINT=https://api.control.cov2.in/api/
          REACT_APP_FIREBASE_CONFIG={"apiKey":"AIzaSyAtDZfhftwpIpN9rZ5I4GHYijGuCbZbib0","authDomain":"hospital-erp-prod.firebaseapp.com","databaseURL":"https://hospital-erp-prod.firebaseio.com","projectId":"hospital-erp-prod","storageBucket":"hospital-erp-prod.appspot.com","messagingSenderId":"374895034375","appId":"1:374895034375:web:68dac98f0009c12906aaa2","measurementId":"G-FMK8FK9CQ1"}'
          write-mode: 'overwrite'

      - name: Read file
        run: cat .env.local

      - name: list files
        run: ls -l

      - name: Yarn Install Dependencies
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - name: npm run build
        run: npm run build

      - name: Log npm errors
        if: failure()
        run: cat /home/runner/.npm/_logs/*

      - name: List build directory
        run: ls -R build/

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'control.covid-prod'
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: 'build'
          DEST_DIR: 'build'

      - name: Invalidate cache
        uses: chetan/invalidate-cloudfront-action@v1.2
        env:
          DISTRIBUTION: ${{ secrets.cloudfront_dist_prod }}
          PATHS: '/*'
          AWS_REGION: 'ap-south-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
